load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

### rules_python
git_repository(
    name = "rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "38f86fb55b698c51e8510c807489c9f4e047480e",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

load("@rules_python//python:pip.bzl", "pip_repositories")
pip_repositories()

### rules_docker
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250",
    strip_prefix = "rules_docker-0.14.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz"],
)

# load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
#     docker_toolchain_configure="toolchain_configure"
# )
# docker_toolchain_configure(
#   name = "docker_config",
#   # # OPTIONAL: Path to a directory which has a custom docker client config.json.
#   # # See https://docs.docker.com/engine/reference/commandline/cli/#configuration-files
#   # # for more details.
#   # client_config="<enter absolute path to your docker config directory here>",
#   # OPTIONAL: Path to the docker binary.
#   # Should be set explcitly for remote execution.
#   docker_path="/usr/local/bin/docker",
#   # # OPTIONAL: Path to the gzip binary.
#   # # Either gzip_path or gzip_target should be set explcitly for remote execution.
#   # gzip_path="<enter absolute path to the gzip binary (in the remote exec env) here>",
#   # # OPTIONAL: Bazel target for the gzip tool.
#   # # Either gzip_path or gzip_target should be set explcitly for remote execution.
#   # gzip_target="<enter absolute path (i.e., must start with repo name @...//:...) to an executable gzip target>",
#   # # OPTIONAL: Path to the xz binary.
#   # # Should be set explcitly for remote execution.
#   # xz_path="<enter absolute path to the xz binary (in the remote exec env) here>",
#   # # OPTIONAL: List of additional flags to pass to the docker command.
#   # docker_flags = [
#   #   "--tls",
#   #   "--log-level=info",
#   # ],
# )

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load(
    "@io_bazel_rules_docker//python3:image.bzl",
    _py3_image_repos = "repositories",
)

_py3_image_repos()

### pip requirements
load("@rules_python//python:pip.bzl", "pip3_import")

pip3_import(
   name = "foo_deps",
   requirements = "//foo:requirements.txt",
)
load("@foo_deps//:requirements.bzl", foo_pip_install = "pip_install")
foo_pip_install()
